# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
src     += Glob('samples/*.c')
libpath = [cwd]
CPPPATH = [cwd]

group = DefineGroup('ble_config', src, depend = ['RT_USING_BLE'], CPPPATH = CPPPATH, LIBPATH = libpath)

Return('group')
