# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
src     += Glob('samples/*.c')
libpath = [cwd]
CPPPATH = [cwd]

group = DefineGroup('lcd_test', src, depend = ['RT_USING_LCD_TEST'], CPPPATH = CPPPATH, LIBPATH = libpath)

Return('group')
