# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.S')
libs    = ['airkiss']
libpath = [cwd]

group = DefineGroup('airkiss', src, depend = ['RT_USING_AIRKISS'], LIBS = libs, LIBPATH = libpath)

Return('group')
