Import('RTT_ROOT')
Import('rtconfig')
from building import *

src  = Glob('*.c')
src += Glob('./real/*.c')

SrcRemove(src, 'polyphase.c')
if rtconfig.PLATFORM == 'iar':
    src += ['./real/arm/asmmisc_iar.s', './real/arm/asmpoly_thumb2_iar.s']
if rtconfig.PLATFORM == 'armcc':
    src += ['./real/arm/asmmisc_rvds.s', './real/arm/asmpoly_thumb2_rvds.s']
if rtconfig.PLATFORM == 'gcc':
    src += ['./real/arm/asmmisc_gcc.s', './real/arm/asmpoly_thumb2_gcc.s']

cwd = GetCurrentDir()
CPPPATH = [cwd, cwd + '/pub']

src = Glob('*.c')
libs  = ['helix_mp3_arm968_gcc']
libpath  = [cwd]

group = DefineGroup('helix_mp3', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
