import os
from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add common files
inc = inc + [cwd]

if GetDepend('PLAYER_USING_EXAMPLE00'): 
    src += Glob('./cmd/cmd_player.c')

if GetDepend('PLAYER_USING_EXAMPLE01'): 
    src += Glob('./cmd/cmd_listplayer.c')

if GetDepend('PLAYER_USING_EXAMPLE02'): 
    src += Glob('./cmd/cmd_codec.c')

if GetDepend('PLAYER_USING_EXAMPLE03'): 
    inc += [os.path.join(GetCurrentDir(), 'tts_player')]
    src += Glob('./tts_player/tts_player.c')
    src += Glob('./tts_player/tts_player_sample.c')

if GetDepend('PLAYER_USING_EXAMPLE04'): 
    src += Glob('./cmd/cmd_pls.c')

# add group to IDE project
objs = DefineGroup('player_example', src, depend = [''], CPPPATH = inc)

Return('objs') 
