# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
libpath = [cwd]
CPPPATH = [cwd]

group = DefineGroup('factory_test', src, depend = ['RT_USING_FACTORYTEST'], CPPPATH = CPPPATH, LIBPATH = libpath)

Return('group')
