# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('rt_ota_port', src, depend = ['PKG_USING_FAL'], CPPPATH = CPPPATH)

Return('group')
