Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')

cwd = GetCurrentDir()
CPPPATH = [cwd]

libs  = ['aac_decoder']
libpath  = [cwd]

group = DefineGroup('aac_decoder', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
