# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.S')
CPPPATH = [cwd]

group = DefineGroup('i2c_sample', src, depend = ['SAMPLE_USING_I2C_SAMPLE'], CPPPATH = CPPPATH)

Return('group')
