# RT-Thread building script for component

Import('RTT_ROOT')
Import('rtconfig')

from building import *

cwd = GetCurrentDir()

src = ['voice_config.c']
CPPPATH = [cwd, cwd + '/include']

libs = ['voice_config_arm968_gcc']
libpath = [cwd + '/libs']

group = DefineGroup('voice_config', src, depend = ['SAMPLE_USING_VOICE_CONFIG'], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
