from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

name = os.path.split(cwd)
group = DefineGroup(str(name[1]), src, depend = [''], CPPPATH = CPPPATH)

Return('group')
