# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.S')
CPPPATH = [cwd]

group = DefineGroup('gpio_sample', src, depend = ['SAMPLE_USING_GPIO_SAMPLE'], CPPPATH = CPPPATH)

Return('group')
