Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, cwd + '/include']
libs  = ['speex_arm968_gcc']
libpath  = [cwd]

group = DefineGroup('speex', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
