Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/include']

libs  = ['opus_arm968_gcc']
libpath  = [cwd]

group = DefineGroup('opus', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
