Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/']

libs  = ['opencore_amr_arm968_gcc']
libpath  = [cwd]

group = DefineGroup('opencore_amr', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
